### ISSUE TITLE
Auto Story Progress

### ISSUE THREAD

**Issue by rayyano0o0** [bdawg1989/NotRaidBot#1]
Hello Gengar Thank you for the great bot

i tried a save data that's 4 stars progress and put a bunch of 5-6 stars seeds in the raidsv the bot changed the story progress to unlock 6 stars and hosted the seeds no problem

the issue is whenever i try to request a pokemon 1-2 stars then it will give an error saying:

"Invalid Story Progress Level... where are you getting your seeds?
Use https://genpkm.com/seeds.html to get them."

i tried seeds from your website and tried some from RaidCalc it gave the same error so i used the same seeds for Rockruff (1 star raid paldea violet and scarlet) but instead of putting (00123139 1 3) **OR** (00123139 1 4) i replaced the one star raid with three and it worked hosting the same exact pokemon with the same exact information (00123139 3 4) so does that mean whenever someone wants to ask for a one or two stars raids they always replace the 1-2 with 3 ?

Edit: i dont know if i can report another issue here but the information keeps resetting in the Active Raid List Collection like the move 1 keeps resetting to go all out and shiny or non shiny keeps resetting to shiny and the battler showdown pokemon keeps deleting whats inside

i hope all of that made sense to you

**Comment by plusReedy** [comment]
When doing low tier raids trying doing them a little like: `ra seed 1 3 ` same with 2 and 3 star raids. 

It seems somewhere on an update with Scarlet/Violet it messed a lot of seeds up.

**Comment by rayyano0o0** [comment]
@plusReedy Thanks for the quick reply but as i mentiond any time i put 1-2 in the stars section it will give an error 

i tried to replacing it to 3 stars ( Applin (1 star) ) (Rockruff (1 Star) ) and it worked so my question was any 1-2 stars i should replace the 1-2 with 3 ?

**Comment by plusReedy** [comment]
Yes, For the raids that wont allow you to do `1 3` or `2 3` place them as `3 3` and if they show the correct raid you're all good.

**Comment by rayyano0o0** [comment]
@plusReedy That was a great help thank you very much

if i can report another issue here is that the information keeps resetting in the Active Raid List Collection like the move 1 keeps resetting to go all out and shiny or non shiny keeps resetting to shiny and the battler showdown pokemon keeps deleting whats inside is there a way to lock the information or maybe like make like a txt file for them to store the information so it cant change or reset ?

**Comment by hexbyt3** [comment]
Edit:  Ok I just checked the code for the bot and fixed the seeds on the site for 1 and 2 star raids.

![image](https://github.com/user-attachments/assets/68f34e61-4ad8-4271-8614-67748be75db6)

![image](https://github.com/user-attachments/assets/70fec432-1f66-4ab2-a8c8-d023ba22d2fd)


So now the website will show 3 3 on the end for 1 and 2 star raids.

![image](https://github.com/user-attachments/assets/1eb325bd-850e-42ba-ad2c-2688c4af505a)

And the bot seems to process that fine.(I tried the crabrawler seed for the test)

![image](https://github.com/user-attachments/assets/2a743a67-a9a1-4cd9-a377-17af48dfea5f)

**Comment by rayyano0o0** [comment]
@bdawg1989 glad i brought something useful :) , thank you

for the other issue (which i don't know if its ok to ask here or in a separate form)

sometimes the bot crash or when you stope it the information inside the collection of the active raid list like shiny move and showdown battler they all got reset, is there a way to make them not reset?

**Comment by hexbyt3** [comment]
For that, anything you change inside the Active Raid list doesn’t save to the config file until you press the stop button which forces a save of all the info. If it crashes, it won’t save to the config.

**Comment by rayyano0o0** [comment]
@bdawg1989 even when you fill them out and host a few raids then stops the bot and start it again they reset its like they dont register or save in the config

**Comment by hexbyt3** [comment]
I just tested one of my bots very thoroughly and could not get it to reset.  Here's what I did:

1.  Set Action Move Bot Should Use to "Move2" and set my battler to "Mewtwo" for 1 of my Blissey raids.
2.  Set Action Move Bot Should Use to "Move3" and set my battler to "Mew" for the 2nd Blissey raid.

Stopped the bot so it could save all of the settings to config.  Re-opened bot and started.

Allowed it to run through several raids and checked again.  Settings are still set where I left them.

**Comment by rayyano0o0** [comment]
@bdawg1989 i did that and i tested one with closing the bot and re opening it, it keeps the info no problem but as soon as i hit start the generate active raids from file turns to False by itself and when i go inside the Active raid collection everything resets (moves Shiny and battler pokemon) i don't know why it keeps resetting for me

**Comment by hexbyt3** [comment]
Yeah the file only needs to import once. After that leave it to false. That’s why it keeps resetting if you turn that to true again. Best to add raids using the arp command. Just replace the rv with arp to add raids to active raid list.

**Comment by rayyano0o0** [comment]
@bdawg1989 i appreciate your patience and help, that was indeed the reason why, thank you :)

**Comment by hexbyt3** [comment]
No problem!
